### ISSUE TITLE
Running `ensync key` with no arguments causes backtrace instead of usage

### ISSUE THREAD

**Issue by pianohacker** [AltSysrq/ensync#1]
[elf]:~> ensync key -- [2017-02-23 22:51] 
    thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:323
    note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by AltSysrq** [comment]
Fixed in 0.1.3.
