### ISSUE TITLE
Allow override of passphrase method/askpass at runtime

### ISSUE THREAD

**Issue by pianohacker** [AltSysrq/ensync#6]
I have my passphrase configured to `ksshaskpass`, to allow background ensync in X. I occasionally need to run ensync from SSH, though, and this requires temporarily changing `general.passphrase` to `prompt`.

It would be convenient to override this per-command.

Maybe:

```console
$ ensync sync ... --passphrase prompt
```

or just

```console
$ ensync sync --passphrase-prompt
```

if you don't want to open up the ability to provide the passphrase as a string on the command line.

**Comment by AltSysrq** [comment]
This is in 1.0.0. The flag is `--key` for consistency with the existing command that supported that exact override.
